# Import statements

In [ ]:
import pandas as pd
import numpy as np

# Creating subsets

In [ ]:
voterCSV = pd.read_csv('/content/NC_Voter_Reg_Nov_23.csv')
voterCSV

,county_desc,election_date,stats_type,precinct_abbrv,vtd_abbrv,party_cd,race_code,ethnic_code,sex_code,age,total_voters,update_date
0,FORSYTH,11/07/2023,voter,065,065,DEM,B,UN,F,Age 18 - 25,5,11/27/2023
1,TRANSYLVANIA,11/07/2023,voter,B2,B2,DEM,U,UN,F,Age 41 - 65,2,11/27/2023
2,CARTERET,11/07/2023,voter,MHD3,MHD3,DEM,W,NL,M,Age Over 66,69,11/27/2023
3,MECKLENBURG,11/07/2023,voter,068,068,UNA,M,HL,M,Age 26 - 40,1,11/27/2023
4,MECKLENBURG,11/07/2023,voter,143,143,REP,W,NL,F,Age 18 - 25,38,11/27/2023
...,...,...,...,...,...,...,...,...,...,...,...,...
636065,GUILFORD,11/07/2023,voter,SUM2,SUM2,REP,W,NL,F,Age 18 - 25,10,11/27/2023
636066,UNION,11/07/2023,voter,018,018,REP,U,NL,F,Age 41 - 65,1,11/27/2023
636067,CUMBERLAND,11/07/2023,voter,CC07,CC07,REP,U,UN,U,Age 41 - 65,2,11/27/2023
636068,FRANKLIN,11/07/2023,voter,19,19,DEM,O,NL,M,Age 26 - 40,1,11/27/2023
636069,YADKIN,11/07/2023,voter,NLIB,NLIB,UNA,O,NL,M,Age 18 - 25,1,11/27/2023

# Filter for Johnston County (Smithfield)

In [ ]:
countyJohnston = voterCSV[voterCSV['county_desc'] == 'JOHNSTON']
countyJohnston = countyJohnston.drop('vtd_abbrv', axis = 1)
countyJohnston

,county_desc,election_date,stats_type,precinct_abbrv,party_cd,race_code,ethnic_code,sex_code,age,total_voters,update_date
107,JOHNSTON,11/07/2023,voter,PR38,UNA,U,UN,U,Age 26 - 40,7,11/27/2023
118,JOHNSTON,11/07/2023,voter,PR27A,UNA,W,UN,F,Age 18 - 25,4,11/27/2023
189,JOHNSTON,11/07/2023,voter,PR32,REP,U,NL,M,Age 18 - 25,1,11/27/2023
243,JOHNSTON,11/07/2023,voter,PR36,DEM,B,NL,F,Age 26 - 40,24,11/27/2023
315,JOHNSTON,11/07/2023,voter,PR29B,UNA,B,UN,F,Age 41 - 65,53,11/27/2023
...,...,...,...,...,...,...,...,...,...,...,...
635899,JOHNSTON,11/07/2023,voter,PR10B,UNA,U,HL,U,Age Over 66,2,11/27/2023
635932,JOHNSTON,11/07/2023,voter,PR11A,UNA,U,NL,U,Age 26 - 40,1,11/27/2023
635982,JOHNSTON,11/07/2023,voter,PR27A,UNA,U,UN,F,Age 41 - 65,3,11/27/2023
635983,JOHNSTON,11/07/2023,voter,PR23A,DEM,B,UN,U,Age Over 66,2,11/27/2023
636016,JOHNSTON,11/07/2023,voter,PR10A,REP,B,UN,F,Age 18 - 25,2,11/27/2023

# Filter for Mecklenberg County (Charlotte)

In [ ]:
countyMecklenberg = voterCSV[voterCSV['county_desc'] == 'MECKLENBURG']
countyMecklenberg['precinct_abbrv'] = countyMecklenberg['precinct_abbrv'].str.replace('PR','', regex = False)
countyMecklenberg = countyMecklenberg.drop('vtd_abbrv', axis = 1)
countyMecklenberg

/tmp/ipython-input-2808568920.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countyMecklenberg['precinct_abbrv'] = countyMecklenberg['precinct_abbrv'].str.replace('PR','', regex = False)

,county_desc,election_date,stats_type,precinct_abbrv,party_cd,race_code,ethnic_code,sex_code,age,total_voters,update_date
3,MECKLENBURG,11/07/2023,voter,068,UNA,M,HL,M,Age 26 - 40,1,11/27/2023
4,MECKLENBURG,11/07/2023,voter,143,REP,W,NL,F,Age 18 - 25,38,11/27/2023
32,MECKLENBURG,11/07/2023,voter,074,UNA,U,HL,F,Age Over 66,1,11/27/2023
41,MECKLENBURG,11/07/2023,voter,100,REP,M,NL,F,Age 26 - 40,1,11/27/2023
63,MECKLENBURG,11/07/2023,voter,021,REP,W,NL,U,Age 26 - 40,6,11/27/2023
...,...,...,...,...,...,...,...,...,...,...,...
635999,MECKLENBURG,11/07/2023,voter,086,UNA,B,UN,F,Age 41 - 65,1,11/27/2023
636028,MECKLENBURG,11/07/2023,voter,064,UNA,U,UN,F,Age 26 - 40,2,11/27/2023
636053,MECKLENBURG,11/07/2023,voter,211,DEM,U,UN,F,Age Over 66,4,11/27/2023
636062,MECKLENBURG,11/07/2023,voter,042,UNA,W,HL,F,Age 26 - 40,1,11/27/2023
636063,MECKLENBURG,11/07/2023,voter,114,DEM,M,UN,F,Age 26 - 40,1,11/27/2023

In [ ]:
'''
We read the csv
'''
voterCSV2022 = pd.read_csv('/content/Registration_Data_July-2022.csv')
countyMecklenberg2022 = voterCSV2022[voterCSV2022['county_desc'] == 'MECKLENBURG']
countyMecklenberg2022 = countyMecklenberg2022.drop('vtd_abbrv', axis = 1)
countyMecklenberg2022

,county_desc,election_date,stats_type,precinct_abbrv,party_cd,race_code,ethnic_code,sex_code,age,total_voters,update_date
11,MECKLENBURG,07/26/2022,voter,228,UNA,A,NL,M,Age 41 - 65,13,07/27/2022
33,MECKLENBURG,07/26/2022,voter,105,DEM,A,NL,F,Age 18 - 25,15,07/27/2022
40,MECKLENBURG,07/26/2022,voter,053,DEM,I,UN,M,Age 41 - 65,1,07/27/2022
42,MECKLENBURG,07/26/2022,voter,232,UNA,A,NL,F,Age 18 - 25,10,07/27/2022
61,MECKLENBURG,07/26/2022,voter,028,DEM,W,UN,F,Age 18 - 25,1,07/27/2022
...,...,...,...,...,...,...,...,...,...,...,...
634068,MECKLENBURG,07/26/2022,voter,079,UNA,U,UN,M,Age 41 - 65,5,07/27/2022
634074,MECKLENBURG,07/26/2022,voter,096,DEM,B,NL,M,Age Over 66,20,07/27/2022
634124,MECKLENBURG,07/26/2022,voter,097,DEM,B,NL,F,Age 18 - 25,40,07/27/2022
634125,MECKLENBURG,07/26/2022,voter,080,UNA,M,UN,F,Age 26 - 40,1,07/27/2022
634171,MECKLENBURG,07/26/2022,voter,227,REP,W,UN,F,Age 18 - 25,14,07/27/2022

# Filter for Randolph County (Asheboro)

In [ ]:
countyRandolph = voterCSV[voterCSV['county_desc'] == 'RANDOLPH']
countyRandolph['precinct_abbrv'] = countyRandolph['precinct_abbrv'].str.replace('PR','', regex = False)
countyRandolph = countyRandolph.drop('vtd_abbrv', axis = 1)
countyRandolph

/tmp/ipython-input-1652008053.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countyRandolph['precinct_abbrv'] = countyRandolph['precinct_abbrv'].str.replace('PR','', regex = False)

,county_desc,election_date,stats_type,precinct_abbrv,party_cd,race_code,ethnic_code,sex_code,age,total_voters,update_date
185,RANDOLPH,11/07/2023,voter,UG,DEM,O,HL,M,Age 18 - 25,2,11/27/2023
346,RANDOLPH,11/07/2023,voter,DR,LIB,O,UN,F,Age 26 - 40,1,11/27/2023
364,RANDOLPH,11/07/2023,voter,TR,UNA,O,NL,M,Age 26 - 40,3,11/27/2023
382,RANDOLPH,11/07/2023,voter,TR,UNA,A,UN,M,Age 26 - 40,2,11/27/2023
396,RANDOLPH,11/07/2023,voter,AR,REP,B,NL,M,Age 18 - 25,2,11/27/2023
...,...,...,...,...,...,...,...,...,...,...,...
635969,RANDOLPH,11/07/2023,voter,SW,REP,W,HL,M,Age 41 - 65,1,11/27/2023
635980,RANDOLPH,11/07/2023,voter,,DEM,U,HL,M,Age 18 - 25,1,11/27/2023
636013,RANDOLPH,11/07/2023,voter,AW,DEM,O,HL,F,Age 26 - 40,2,11/27/2023
636034,RANDOLPH,11/07/2023,voter,UG,LIB,W,UN,M,Age 26 - 40,2,11/27/2023
636060,RANDOLPH,11/07/2023,voter,AW,UNA,A,UN,F,Age 26 - 40,1,11/27/2023

# We download the csvs

In [ ]:
'''
This is our download command for loading the filtered csv once we have decided which csvs we want to keep.
'''
countyJohnston = countyJohnston.to_csv('Smithfield_CSV.csv')
countyMecklenberg = countyMecklenberg.to_csv('Charlotte_CSV.csv')
countyRandolph = countyRandolph.to_csv('Asheboro_CSV.csv')
countyMecklenberg2022 = countyMecklenberg2022.to_csv('Charlotte_2022_CSV.csv')